import 'package:flutter/material.dart';
import 'package:audio_wave/audio_wave.dart';

class BackgroundAudioWave extends StatelessWidget {
  const BackgroundAudioWave({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: AudioWave(
        height: 45,
        width: 204,
        spacing: 1.5,
        animation: false,
        bars: [
          AudioWaveBar(height: 70, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 40, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 5, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 40, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 60, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 70, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 60, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 70, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 60, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 50, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 10, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 30, color: const Color(0xffB3B5D8)),
          AudioWaveBar(height: 20, color: const Color(0xffB3B5D8)),
        ],
      ),
      width: 208,
    );
  }
}
