import 'package:flutter/material.dart';
import 'package:audio_wave/audio_wave.dart';

class ForegroundAudioWave extends StatelessWidget {
  final bool animated;
  const ForegroundAudioWave({
    Key? key,
  this.animated = true
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: AudioWave(
        height: 45,
        width: 204,
        spacing: 1.5,
        animationLoop: 1,
        animation: animated,
        bars: [
          AudioWaveBar(height: 70, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 40, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 5, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 40, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 60, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 70, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 60, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 70, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 60, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 50, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 10, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 30, color: const Color(0xff6A64AA)),
          AudioWaveBar(height: 20, color: const Color(0xff6A64AA)),
        ],
      ),
      width: 208,
    );
  }
}
